#!/usr/bin/env python

import robot_upstart
import os

j = robot_upstart.Job(name="youbot-core", workspace_setup=os.environ.get('ROBOT_SETUP'))

# Stuff to launch on system startup.
j.add(package="youbot_bringup", glob="launch/*")

j.install()
